---
- name: Remove old packages
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
  - docker
  - docker-engine
  - docker.io
  tags:
    - docker
    - install

- name: Install docker dependencies
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common
  - apt-transport-https
  - python-pip
  - python-setuptools
  - python-docker
  tags:
    - docker
    - install

- name: Install python docker module
  pip:
    name: docker-py
    state: present
  become: true
  tags:
    - docker
    - install

- name: Import the docker GPG key into apt
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  tags:
    - docker
    - install

- name: Add docker deb repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  tags:
    - docker
    - install

- name: Install Docker
  apt:
    pkg: docker-ce
    state: installed
    update_cache: yes
  tags:
    - docker
    - install

